version: 2.1

jobs:
  docker_bench_security:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - run:
          name: Docker Bench for Security
          command: |
            curl -sSL https://github.com/docker/docker-bench-security/releases/download/v1.3.1/docker-bench-security.tar.gz | tar xz
            cd docker-bench-security
            sudo ./docker-bench-security.sh

workflows:
  version: 2
  build:
    jobs:
      - docker_bench_security
